name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Setup Playwright browsers cache
        uses: actions/cache@v4.2.3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps chromium firefox webkit

      - name: Run tests
        run: pnpm test

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: |
            **/src/__screenshots__/**/*.png

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier check
        run: pnpm prettier --check .

      - name: Run ESLint
        run: pnpm eslint --max-warnings 0
